# Lesson 07 module — NOTE what's missing: no `provider` block and no
# `terraform { required_providers }` block! Both are GENERATED by the wrapper.
# This keeps the module reusable: the wrapper decides provider + versions.

variable "environment" { type = string }
variable "message" {
  type    = string
  default = "generated providers work!"
}

resource "local_file" "demo" {
  filename = "${path.module}/demo-${var.environment}.txt"
  content  = "${var.message}\n"
}

output "file_path" {
  value = local_file.demo.filename
}
